name: Metrics
on:
  # Schedule updates (every 12 hours)
  schedule: [{cron: "0 */12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@{dmyna/lowlighter-metrics}
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: dmyna
          template: classic
          base: repositories, metadata
          config_timezone: UTC
          plugin_activity: no
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 20
          plugin_activity_visibility: all
          commits_authoring: dmyna
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_other: false
          plugin_languages_limit: 10,
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_analysis_timeout_repositories: 15
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_topics: no
          plugin_topics_limit: 30
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_gists: yes
          plugin_code: yes
          plugin_code_languages: rust, typescript, javascript, lua, nix, bash, sass, html, css
